name: Check and fix code styling with php-cs-fixer

on: [ pull_request, push ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.10.0
        with:
          commit_message: Automatically applied php-cs-fixer changes
          branch: ${{ steps.extract_branch.outputs.branch }}
